import argparse
import collections
import json
import os
import sys
import urllib.error
import urllib.request

from . import __version__

IGNORE_DIRS = set([".git", ".hg", ".svn", "node_modules", "build", "dist", ".venv", "__pycache__", ".idea", ".vscode"])
LANG_BY_EXT = {
    ".py": "Python",
    ".ts": "TypeScript",
    ".tsx": "TypeScript React",
    ".js": "JavaScript",
    ".jsx": "JavaScript React",
    ".ets": "ArkTS",
    ".java": "Java",
    ".kt": "Kotlin",
    ".swift": "Swift",
    ".go": "Go",
    ".rs": "Rust",
    ".md": "Markdown",
}
ENTRY_NAMES = ["README.md", "package.json", "pyproject.toml", "Cargo.toml", "go.mod", "build.gradle", "oh-package.json5", "pubspec.yaml"]


def walk_repo(repo, max_files, extra_ignore=None):
    records = []
    ignore_dirs = set(IGNORE_DIRS)
    if extra_ignore:
        ignore_dirs.update(extra_ignore)
    for root, dirs, files in os.walk(repo):
        dirs[:] = [item for item in dirs if item not in ignore_dirs and not item.startswith(".cache")]
        for filename in files:
            path = os.path.join(root, filename)
            rel = os.path.relpath(path, repo)
            if len(records) >= max_files:
                return records
            if os.path.getsize(path) > 300000:
                continue
            records.append(rel)
    return records


def top_dirs(files):
    counts = collections.Counter()
    for path in files:
        part = path.split(os.sep)[0]
        counts[part] += 1
    return counts.most_common(12)


def languages(files):
    counts = collections.Counter()
    for path in files:
        _, ext = os.path.splitext(path)
        lang = LANG_BY_EXT.get(ext)
        if lang:
            counts[lang] += 1
    return counts.most_common()


def entry_files(repo, files):
    entries = []
    names = set(ENTRY_NAMES)
    for path in files:
        if os.path.basename(path) in names or path.lower().endswith(("main.py", "index.ts", "index.js", "app.tsx", "main.ets")):
            entries.append(path)
    return entries[:20]


def command_hints(files):
    file_set = set(files)
    hints = []
    if "pyproject.toml" in file_set:
        hints.append(("Install", "python3 -m pip install -e ."))
        hints.append(("Test", "python3 -m unittest discover -s tests"))
    if "package.json" in file_set:
        hints.append(("Install", "npm install"))
        hints.append(("Run", "npm run dev"))
        hints.append(("Test", "npm test"))
    if "Cargo.toml" in file_set:
        hints.append(("Run", "cargo run"))
        hints.append(("Test", "cargo test"))
    if "go.mod" in file_set:
        hints.append(("Run", "go run ./..."))
        hints.append(("Test", "go test ./..."))
    if "pubspec.yaml" in file_set:
        hints.append(("Install", "flutter pub get"))
        hints.append(("Test", "flutter test"))
    if "oh-package.json5" in file_set:
        hints.append(("Install", "ohpm install"))
        hints.append(("Build", "hvigorw assembleHap"))
    return hints


def tree_lines(files, max_depth=3, limit=80):
    output = []
    seen_dirs = set()
    count = 0
    for path in sorted(files):
        if count >= limit:
            output.append("...")
            break
        parts = path.split(os.sep)
        capped = parts[:max_depth]
        for depth, part in enumerate(capped):
            is_dir = depth < len(parts) - 1
            key = tuple(capped[:depth + 1])
            if is_dir and key in seen_dirs:
                continue
            if is_dir:
                seen_dirs.add(key)
            indent = "  " * depth
            suffix = "/" if is_dir else ""
            output.append("%s%s%s" % (indent, part, suffix))
            count += 1
    return output


def read_short(repo, path):
    full = os.path.join(repo, path)
    try:
        with open(full, "r", encoding="utf-8") as handle:
            return handle.read(2500)
    except Exception:
        return ""


def repo_data(repo, files):
    repo_name = os.path.basename(os.path.abspath(repo))
    return {
        "repo_name": repo_name,
        "file_count": len(files),
        "languages": [{"name": name, "files": count} for name, count in languages(files)],
        "top_level_areas": [{"name": name, "files": count} for name, count in top_dirs(files)],
        "entry_files": entry_files(repo, files),
        "command_hints": [{"kind": kind, "command": command} for kind, command in command_hints(files)],
        "first_questions": [
            "What command starts the project locally?",
            "Which tests should run before opening a PR?",
            "Which folders are generated or vendor code?",
            "What coding conventions are expected but not enforced by tooling?",
        ],
    }


def render(repo, files, include_tree=False):
    data = repo_data(repo, files)
    langs = data["languages"]
    entries = data["entry_files"]
    output = ["# %s Onboarding Guide" % data["repo_name"], "", "Generated by repo-onboard-ai.", ""]
    output.append("## What This Repo Looks Like")
    output.append("")
    if langs:
        output.append("Main languages:")
        for item in langs[:8]:
            output.append("- %s: %d file(s)" % (item["name"], item["files"]))
    else:
        output.append("No obvious source language detected from file extensions.")
    output.append("")
    output.append("Top-level areas:")
    for item in data["top_level_areas"]:
        output.append("- `%s`: %d file(s)" % (item["name"], item["files"]))
    output.append("")
    if data["command_hints"]:
        output.append("## Command Hints")
        output.append("")
        for item in data["command_hints"]:
            output.append("- %s: `%s`" % (item["kind"], item["command"]))
    if include_tree:
        output.append("")
        output.append("## Repository Tree")
        output.append("")
        output.append("```text")
        output.extend(tree_lines(files))
        output.append("```")
    output.append("")
    output.append("## Suggested Reading Order")
    output.append("")
    if entries:
        for index, path in enumerate(entries[:10], 1):
            output.append("%d. `%s`" % (index, path))
    else:
        output.append("1. Start with the root README or the main package manifest.")
    output.append("")
    output.append("## Likely Entry Points")
    output.append("")
    for path in entries[:20]:
        output.append("- `%s`" % path)
    output.append("")
    output.append("## First Questions For Maintainers")
    output.append("")
    output.extend("- %s" % item for item in data["first_questions"])
    output.append("")
    readme = "README.md" if "README.md" in files else ""
    if readme:
        output.append("## README Snapshot")
        output.append("")
        output.append("````markdown")
        output.append(read_short(repo, readme).strip())
        output.append("````")
        output.append("")
    return "\n".join(output)


def call_ai(repo_summary, draft, model=None, base_url=None):
    api_key = os.getenv("AI_API_KEY")
    if not api_key:
        raise RuntimeError("AI_API_KEY is not set")
    base_url = (base_url or os.getenv("AI_BASE_URL", "https://api.openai.com/v1")).rstrip("/")
    model = model or os.getenv("AI_MODEL", "gpt-4o-mini")
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "Return only Markdown. Write a helpful onboarding guide for new contributors."},
            {"role": "user", "content": "Improve this repository onboarding guide without inventing commands.\n\nSUMMARY:\n%s\n\nDRAFT:\n%s" % (repo_summary[:8000], draft[:10000])},
        ],
        "temperature": 0.2,
    }
    request = urllib.request.Request(
        base_url + "/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Authorization": "Bearer " + api_key, "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise RuntimeError("AI request failed: %s" % exc)
    return body["choices"][0]["message"]["content"].strip() + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate ONBOARDING.md for a repository.")
    parser.add_argument("--repo", default=".", help="Repository path")
    parser.add_argument("--max-files", type=int, default=800, help="Maximum files to scan")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown", help="Output format")
    parser.add_argument("--tree", action="store_true", help="Include a compact repository tree in Markdown output")
    parser.add_argument("--ignore", action="append", default=[], help="Additional directory name to ignore; repeatable")
    parser.add_argument("--ai", action="store_true", help="Use an OpenAI-compatible model")
    parser.add_argument("--model", help="Override AI_MODEL for --ai")
    parser.add_argument("--base-url", help="Override AI_BASE_URL for --ai")
    parser.add_argument("--output", help="Write result to a file")
    parser.add_argument("--version", action="version", version="repo-onboard-ai %s" % __version__)
    args = parser.parse_args(argv)
    files = walk_repo(args.repo, args.max_files, args.ignore)
    if args.format == "json":
        draft = json.dumps(repo_data(args.repo, files), ensure_ascii=False, indent=2) + "\n"
    else:
        draft = render(args.repo, files, args.tree)
    summary = "\n".join(files[:300])
    result = call_ai(summary, draft, args.model, args.base_url) if args.ai else draft
    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(result)
    else:
        sys.stdout.write(result)


if __name__ == "__main__":
    main()
