import argparse
import collections
import json
import os
import sys
import urllib.error
import urllib.request


IGNORE_DIRS = set([".git", ".hg", ".svn", "node_modules", "build", "dist", ".venv", "__pycache__", ".idea", ".vscode"])
LANG_BY_EXT = {
    ".py": "Python",
    ".ts": "TypeScript",
    ".tsx": "TypeScript React",
    ".js": "JavaScript",
    ".jsx": "JavaScript React",
    ".ets": "ArkTS",
    ".java": "Java",
    ".kt": "Kotlin",
    ".swift": "Swift",
    ".go": "Go",
    ".rs": "Rust",
    ".md": "Markdown",
}
ENTRY_NAMES = ["README.md", "package.json", "pyproject.toml", "Cargo.toml", "go.mod", "build.gradle", "oh-package.json5", "pubspec.yaml"]


def walk_repo(repo, max_files):
    records = []
    for root, dirs, files in os.walk(repo):
        dirs[:] = [item for item in dirs if item not in IGNORE_DIRS and not item.startswith(".cache")]
        for filename in files:
            path = os.path.join(root, filename)
            rel = os.path.relpath(path, repo)
            if len(records) >= max_files:
                return records
            if os.path.getsize(path) > 300000:
                continue
            records.append(rel)
    return records


def top_dirs(files):
    counts = collections.Counter()
    for path in files:
        part = path.split(os.sep)[0]
        counts[part] += 1
    return counts.most_common(12)


def languages(files):
    counts = collections.Counter()
    for path in files:
        _, ext = os.path.splitext(path)
        lang = LANG_BY_EXT.get(ext)
        if lang:
            counts[lang] += 1
    return counts.most_common()


def entry_files(repo, files):
    entries = []
    names = set(ENTRY_NAMES)
    for path in files:
        if os.path.basename(path) in names or path.lower().endswith(("main.py", "index.ts", "index.js", "app.tsx", "main.ets")):
            entries.append(path)
    return entries[:20]


def read_short(repo, path):
    full = os.path.join(repo, path)
    try:
        with open(full, "r", encoding="utf-8") as handle:
            return handle.read(2500)
    except Exception:
        return ""


def render(repo, files):
    repo_name = os.path.basename(os.path.abspath(repo))
    langs = languages(files)
    entries = entry_files(repo, files)
    output = ["# %s Onboarding Guide" % repo_name, "", "Generated by repo-onboard-ai.", ""]
    output.append("## What This Repo Looks Like")
    output.append("")
    if langs:
        output.append("Main languages:")
        for name, count in langs[:8]:
            output.append("- %s: %d file(s)" % (name, count))
    else:
        output.append("No obvious source language detected from file extensions.")
    output.append("")
    output.append("Top-level areas:")
    for name, count in top_dirs(files):
        output.append("- `%s`: %d file(s)" % (name, count))
    output.append("")
    output.append("## Suggested Reading Order")
    output.append("")
    if entries:
        for index, path in enumerate(entries[:10], 1):
            output.append("%d. `%s`" % (index, path))
    else:
        output.append("1. Start with the root README or the main package manifest.")
    output.append("")
    output.append("## Likely Entry Points")
    output.append("")
    for path in entries[:20]:
        output.append("- `%s`" % path)
    output.append("")
    output.append("## First Questions For Maintainers")
    output.append("")
    output.extend([
        "- What command starts the project locally?",
        "- Which tests should run before opening a PR?",
        "- Which folders are generated or vendor code?",
        "- What coding conventions are expected but not enforced by tooling?",
    ])
    output.append("")
    readme = "README.md" if "README.md" in files else ""
    if readme:
        output.append("## README Snapshot")
        output.append("")
        output.append("````markdown")
        output.append(read_short(repo, readme).strip())
        output.append("````")
        output.append("")
    return "\n".join(output)


def call_ai(repo_summary, draft):
    api_key = os.getenv("AI_API_KEY")
    if not api_key:
        raise RuntimeError("AI_API_KEY is not set")
    base_url = os.getenv("AI_BASE_URL", "https://api.openai.com/v1").rstrip("/")
    model = os.getenv("AI_MODEL", "gpt-4o-mini")
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "Return only Markdown. Write a helpful onboarding guide for new contributors."},
            {"role": "user", "content": "Improve this repository onboarding guide without inventing commands.\n\nSUMMARY:\n%s\n\nDRAFT:\n%s" % (repo_summary[:8000], draft[:10000])},
        ],
        "temperature": 0.2,
    }
    request = urllib.request.Request(
        base_url + "/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Authorization": "Bearer " + api_key, "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise RuntimeError("AI request failed: %s" % exc)
    return body["choices"][0]["message"]["content"].strip() + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate ONBOARDING.md for a repository.")
    parser.add_argument("--repo", default=".", help="Repository path")
    parser.add_argument("--max-files", type=int, default=800, help="Maximum files to scan")
    parser.add_argument("--ai", action="store_true", help="Use an OpenAI-compatible model")
    parser.add_argument("--output", help="Write result to a file")
    args = parser.parse_args(argv)
    files = walk_repo(args.repo, args.max_files)
    draft = render(args.repo, files)
    summary = "\n".join(files[:300])
    result = call_ai(summary, draft) if args.ai else draft
    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(result)
    else:
        sys.stdout.write(result)


if __name__ == "__main__":
    main()
